name: 'tsl-merge'

on:
  # Trigger the workflow on push or manually
  push:
    branches: ['main']

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Setup latest Alpine Linux
        uses: jirutka/setup-alpine@v1.1.4
        with:
          arch: aarch64
          packages: >
            g++
            cmake
            make
            openssh
            ninja
            autoconf
            dos2unix
            wget
            xz
            tar
            rsync
            python3
            git
            util-linux
            py3-pip
            py3-babel
            py3-lxml
            py3-markupsafe
            py3-matplotlib
            py3-numpy
            py3-pandas
            py3-pillow
            py3-scipy
            py3-networkx
            py3-jinja2
            libstdc++
            freetype-dev
            libpng-dev
            openblas-dev
            py-yaml
            graphviz-dev
            linux-headers
            libffi-dev
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: TEST
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: db-tu-dresden/TSL
          path: TSL
      - name: Install Python dependencies into alpine shell
        run: |
          pip install -r ./TEST/requirements.txt
        shell: alpine.sh {0}          
      - name: Generate TSL for neon and asimd
        run: |
          cd TSL
          python main.py --targets neon asimd -o tsl_lib
          cmake -S . -B tsl -DUSE_EXISTING_TSL_PATH=./tsl_lib
          make -j -C tsl
        shell: alpine.sh {0}